options(digits = 3)
library(matrixStats)
library(tidyverse)
library(caret)
library(dslabs)
data(brca)
#dim(brca$x)
#mean(brca$y == 'M')
cm <-colMeans(brca$x)
csd <- colSds(brca$x) 
nsx <- sweep(sweep(brca$x, 2, cm),2,csd,FUN = '/')
#median(nsx[,1])
edx <- as.matrix(dist(nsx)) # calculating elucidian distances between all observations
idx = which(brca$y == 'B')
mean(edx[1,idx[-1]])
idx = which(brca$y == 'M')
mean(edx[1,idx])
heatmap(as.matrix(dist(t(nsx))), labRow = NA, labCol = NA)
# hc <- hclust(dist(t(nsx)), method = 'average')
# plot(hc)
# ct <- cutree(hc, k = 5)
# split(names(ct), ct)
# plot(hc)
# rect.hclust(hc , k = 5, border = 2:6)
# abline(h = 5, col = 'red')
h <- hclust(dist(t(nsx)))
groups <- cutree(h, k = 5)
split(names(groups), groups)
pc <- prcomp(nsx)
summary(pc)
plot(pc$x[,'PC1'],pc$x[,'PC2'], col = brca$y)
legend('topright', legend = levels(brca$y), col = palette(), cex = 0.8, pch = 1)
for (i in 1:10) {
boxplot(pc$x[,i] ~ brca$y, main = paste("PC", i))
}
